// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js

import { createServiceRegistry, ServiceMethodHandler, StreamingMethodHandler } from "../grpc-service"
import { StreamingResponseHandler } from "../grpc-handler"
import { registerAllMethods } from "./methods"

// Create memory service registry
const memoryService = createServiceRegistry("memory")

// Export the method handler types and registration function
export type MemoryMethodHandler = ServiceMethodHandler
export type MemoryStreamingMethodHandler = StreamingMethodHandler
export const registerMethod = memoryService.registerMethod

// Export the request handlers
export const handleMemoryServiceRequest = memoryService.handleRequest
export const handleMemoryServiceStreamingRequest = memoryService.handleStreamingRequest
export const isStreamingMethod = memoryService.isStreamingMethod

// Register all memory methods
registerAllMethods()
