// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js

// Import all method implementations
import { registerMethod } from "./index"
import { AnalyzeConversation } from "./AnalyzeConversation"
import { ClearProjectMemory } from "./ClearProjectMemory"
import { ExportMemory } from "./ExportMemory"
import { GetCurrentProjectMemory } from "./GetCurrentProjectMemory"
import { GetMemoryStats } from "./GetMemoryStats"
import { GetRelevantContext } from "./GetRelevantContext"
import { ImportMemory } from "./ImportMemory"
import { initializeMemoryService } from "./initializeMemoryService"

// Register all memory service methods
export function registerAllMethods(): void {
	// Register each method with the registry
	registerMethod("AnalyzeConversation", AnalyzeConversation)
	registerMethod("ClearProjectMemory", ClearProjectMemory)
	registerMethod("ExportMemory", ExportMemory)
	registerMethod("GetCurrentProjectMemory", GetCurrentProjectMemory)
	registerMethod("GetMemoryStats", GetMemoryStats)
	registerMethod("GetRelevantContext", GetRelevantContext)
	registerMethod("ImportMemory", ImportMemory)
	registerMethod("initializeMemoryService", initializeMemoryService)
}
