"use strict"
// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js
Object.defineProperty(exports, "__esModule", { value: true })
exports.MemoryServiceClient =
	exports.UiServiceClient =
	exports.SlashServiceClient =
	exports.ModelsServiceClient =
	exports.WebServiceClient =
	exports.TaskServiceClient =
	exports.StateServiceClient =
	exports.McpServiceClient =
	exports.FileServiceClient =
	exports.CheckpointsServiceClient =
	exports.BrowserServiceClient =
	exports.AccountServiceClient =
		void 0
const grpc_client_base_1 = require("./grpc-client-base")
const account_1 = require("@shared/proto/account")
const browser_1 = require("@shared/proto/browser")
const checkpoints_1 = require("@shared/proto/checkpoints")
const file_1 = require("@shared/proto/file")
const mcp_1 = require("@shared/proto/mcp")
const state_1 = require("@shared/proto/state")
const task_1 = require("@shared/proto/task")
const web_1 = require("@shared/proto/web")
const models_1 = require("@shared/proto/models")
const slash_1 = require("@shared/proto/slash")
const ui_1 = require("@shared/proto/ui")
const memory_1 = require("@shared/proto/memory")
const AccountServiceClient = (0, grpc_client_base_1.createGrpcClient)(account_1.AccountServiceDefinition)
exports.AccountServiceClient = AccountServiceClient
const BrowserServiceClient = (0, grpc_client_base_1.createGrpcClient)(browser_1.BrowserServiceDefinition)
exports.BrowserServiceClient = BrowserServiceClient
const CheckpointsServiceClient = (0, grpc_client_base_1.createGrpcClient)(checkpoints_1.CheckpointsServiceDefinition)
exports.CheckpointsServiceClient = CheckpointsServiceClient
const FileServiceClient = (0, grpc_client_base_1.createGrpcClient)(file_1.FileServiceDefinition)
exports.FileServiceClient = FileServiceClient
const McpServiceClient = (0, grpc_client_base_1.createGrpcClient)(mcp_1.McpServiceDefinition)
exports.McpServiceClient = McpServiceClient
const StateServiceClient = (0, grpc_client_base_1.createGrpcClient)(state_1.StateServiceDefinition)
exports.StateServiceClient = StateServiceClient
const TaskServiceClient = (0, grpc_client_base_1.createGrpcClient)(task_1.TaskServiceDefinition)
exports.TaskServiceClient = TaskServiceClient
const WebServiceClient = (0, grpc_client_base_1.createGrpcClient)(web_1.WebServiceDefinition)
exports.WebServiceClient = WebServiceClient
const ModelsServiceClient = (0, grpc_client_base_1.createGrpcClient)(models_1.ModelsServiceDefinition)
exports.ModelsServiceClient = ModelsServiceClient
const SlashServiceClient = (0, grpc_client_base_1.createGrpcClient)(slash_1.SlashServiceDefinition)
exports.SlashServiceClient = SlashServiceClient
const UiServiceClient = (0, grpc_client_base_1.createGrpcClient)(ui_1.UiServiceDefinition)
exports.UiServiceClient = UiServiceClient
const MemoryServiceClient = (0, grpc_client_base_1.createGrpcClient)(memory_1.MemoryServiceDefinition)
exports.MemoryServiceClient = MemoryServiceClient
//# sourceMappingURL=grpc-client.js.map
