"use strict";
// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.isStreamingMethod = exports.handleUriServiceStreamingRequest = exports.handleUriServiceRequest = exports.registerMethod = void 0;
const host_grpc_service_1 = require("../host-grpc-service");
const methods_1 = require("./methods");
// Create uri service registry
const uriService = (0, host_grpc_service_1.createServiceRegistry)("uri");
exports.registerMethod = uriService.registerMethod;
// Export the request handlers
exports.handleUriServiceRequest = uriService.handleRequest;
exports.handleUriServiceStreamingRequest = uriService.handleStreamingRequest;
exports.isStreamingMethod = uriService.isStreamingMethod;
// Register all uri methods
(0, methods_1.registerAllMethods)();
//# sourceMappingURL=index.js.map