"use strict";
// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.registerAllMethods = registerAllMethods;
// Import all method implementations
const index_1 = require("./index");
const file_1 = require("./file");
const joinPath_1 = require("./joinPath");
const parse_1 = require("./parse");
// Register all uri service methods
function registerAllMethods() {
    // Register each method with the registry
    (0, index_1.registerMethod)("file", file_1.file);
    (0, index_1.registerMethod)("joinPath", joinPath_1.joinPath);
    (0, index_1.registerMethod)("parse", parse_1.parse);
}
//# sourceMappingURL=methods.js.map