"use strict";
// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.isStreamingMethod = exports.handleWatchServiceStreamingRequest = exports.handleWatchServiceRequest = exports.registerMethod = void 0;
const host_grpc_service_1 = require("../host-grpc-service");
const methods_1 = require("./methods");
// Create watch service registry
const watchService = (0, host_grpc_service_1.createServiceRegistry)("watch");
exports.registerMethod = watchService.registerMethod;
// Export the request handlers
exports.handleWatchServiceRequest = watchService.handleRequest;
exports.handleWatchServiceStreamingRequest = watchService.handleStreamingRequest;
exports.isStreamingMethod = watchService.isStreamingMethod;
// Register all watch methods
(0, methods_1.registerAllMethods)();
//# sourceMappingURL=index.js.map