"use strict";
// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.streamingMethods = void 0;
exports.registerAllMethods = registerAllMethods;
// Import all method implementations
const index_1 = require("./index");
const subscribeToFile_1 = require("./subscribeToFile");
// Streaming methods for this service
exports.streamingMethods = [
    "subscribeToFile"
];
// Register all watch service methods
function registerAllMethods() {
    // Register each method with the registry
    (0, index_1.registerMethod)("subscribeToFile", subscribeToFile_1.subscribeToFile, { isStreaming: true });
}
//# sourceMappingURL=methods.js.map