// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js

// Import all method implementations
import { registerMethod } from "./index"
import { onDidShowAnnouncement } from "./onDidShowAnnouncement"
import { scrollToSettings } from "./scrollToSettings"
import { subscribeToAccountButtonClicked } from "./subscribeToAccountButtonClicked"
import { subscribeToAddToInput } from "./subscribeToAddToInput"
import { subscribeToChatButtonClicked } from "./subscribeToChatButtonClicked"
import { subscribeToHistoryButtonClicked } from "./subscribeToHistoryButtonClicked"
import { subscribeToMcpButtonClicked } from "./subscribeToMcpButtonClicked"

// Streaming methods for this service
export const streamingMethods = [
	"subscribeToAddToInput",
	"subscribeToMcpButtonClicked",
	"subscribeToHistoryButtonClicked",
	"subscribeToChatButtonClicked",
	"subscribeToAccountButtonClicked",
]

// Register all ui service methods
export function registerAllMethods(): void {
	// Register each method with the registry
	registerMethod("onDidShowAnnouncement", onDidShowAnnouncement)
	registerMethod("scrollToSettings", scrollToSettings)
	registerMethod("subscribeToAccountButtonClicked", subscribeToAccountButtonClicked, { isStreaming: true })
	registerMethod("subscribeToAddToInput", subscribeToAddToInput, { isStreaming: true })
	registerMethod("subscribeToChatButtonClicked", subscribeToChatButtonClicked, { isStreaming: true })
	registerMethod("subscribeToHistoryButtonClicked", subscribeToHistoryButtonClicked, { isStreaming: true })
	registerMethod("subscribeToMcpButtonClicked", subscribeToMcpButtonClicked, { isStreaming: true })
}
